export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_QUESTION_SELECT = 'TOGGLE_QUESTION_SELECT';
export const NEW_SESSIONS = 'NEW_SESSIONS';
export const NEW_STATUS = 'NEW_STATUS';
export const BOOTSTRAP = 'BOOTSTRAP';
